### PR TITLE
TypeScript

### PR DESCRIPTION
**Pull request by taoqf**
Could this version be published under `dev`(or other) tag? @atian25

### CODE REVIEW

**Comment by taoqf** [comment]
I give up. Could not pass all the tests in node4. Maybe you guys could do the tests for me.

**Comment by atian25** [comment]
for now, we could drop node 4 support.

and this  PR is really a big break change, tag or branch is hard to maintain,  I prefer to separate to a standalone project.

**Comment by taoqf** [comment]
You are the boss.

**Comment by taoqf** [comment]
I believe it will work under node4 now.

**Pull request closed without merging**
